name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v3.3.0
        with:
          username: 'rafaelwassoaski'
          password: ${{secrets.docker_hub}}
          

      - name: docker build
        uses: actions/setup-node@v2
    
          
